export const images = [
    {
        id: 1,
        src: '/images/lake.jpg',
        //src: "https://media.istockphoto.com/id/470172598/photo/hanging-out.jpg?s=2048x2048&w=is&k=20&c=hqH-1a2LWVnTDameLchNu2EJfbTCqZUMH_LQ8sN3fkc=",
        title: "THE",
        desc: "GRAND",
        descrption: "TOUR SLAES",
    },
    {
        id: 3,
        src: '/images/lake.jpg',
        //src: "https://media.istockphoto.com/id/470172598/photo/hanging-out.jpg?s=2048x2048&w=is&k=20&c=hqH-1a2LWVnTDameLchNu2EJfbTCqZUMH_LQ8sN3fkc=",
        title: "THE",
        desc: "GRAND",
        descrption: "TOUR SLAES",
    },
    {
        id: 6,
        src: '/images/devanca.jpg',
        //src: "https://media.istockphoto.com/id/470172598/photo/hanging-out.jpg?s=2048x2048&w=is&k=20&c=hqH-1a2LWVnTDameLchNu2EJfbTCqZUMH_LQ8sN3fkc=",
        title: "THE",
        desc: "GRAND",
        descrption: "TOUR SLAES",
    },
    {
        id: 4,
        src: '/images/animal.jpg',
        //src: "https://media.istockphoto.com/id/470172598/photo/hanging-out.jpg?s=2048x2048&w=is&k=20&c=hqH-1a2LWVnTDameLchNu2EJfbTCqZUMH_LQ8sN3fkc=",
        title: "THE",
        desc: "GRAND",
        descrption: "TOUR SLAES",
    }
    ,
    {
        id: 5,
        src: '/images/iceback.jpg',
        //src: "https://media.istockphoto.com/id/470172598/photo/hanging-out.jpg?s=2048x2048&w=is&k=20&c=hqH-1a2LWVnTDameLchNu2EJfbTCqZUMH_LQ8sN3fkc=",
        title: "THE",
        desc: "GRAND",
        descrption: "TOUR SLAES",
    },
    // {
    //     id: 5,
    //     src: '/images/devance_cover_photo.jpg',
    //     //src: "https://media.istockphoto.com/id/470172598/photo/hanging-out.jpg?s=2048x2048&w=is&k=20&c=hqH-1a2LWVnTDameLchNu2EJfbTCqZUMH_LQ8sN3fkc=",
    //     title: "THE",
    //     desc: "GRAND",
    //     descrption: "TOUR SLAES",
    // }
    // {
    //     id: 1,
    //     src: "https://res.cloudinary.com/doamgn1l0/image/upload/v1705781708/phaozusyhgheyyawehzv.jpg",
    //     title: "THE",
    //     desc: "GRAND",
    //     descrption: "TOUR SLAES",
    // },
    // {
    //     id: 1,
    //     src: "https://res.cloudinary.com/doamgn1l0/image/upload/v1707211458/hhd7pewnbznwpgfgjcie.jpg",
    //     title: "THE",
    //     desc: "GRAND",
    //     descrption: "TOUR SLAES",
    // },
    //  {
    //     id: 1,
    //     src: "https://res.cloudinary.com/doamgn1l0/image/upload/v1707145877/vakshzjztsftiwijvjtl.jpg",
    //     title: "THE",
    //     desc: "GRAND",
    //     descrption: "TOUR SLAES",
    // },
    // {
    //     id: 1,
    //     src: "https://res.cloudinary.com/doamgn1l0/image/upload/v1707144994/ekts65zzcmtvgwzqrgrd.jpg",
    //     title: "THE",
    //     desc: "GRAND",
    //     descrption: "TOUR SLAES",
    // },
    // {
    //     id: 1,
    //     src: "https://res.cloudinary.com/doamgn1l0/image/upload/v1705579729/ifg1uhhh4vpe1ofznvgt.jpg",
    //     title: "THE",
    //     desc: "GRAND",
    //     descrption: "TOUR SLAES",
    // }
]